-- 
-- TABLE: ACTIVIDAD_PARTICIPACION 
--

CREATE TABLE ACTIVIDAD_PARTICIPACION(
    ACTIVIDAD_PARTICIPACION_ID               VARCHAR2(40)     NOT NULL,
    RACTVIDAD_ID                             VARCHAR2(40)     NOT NULL,
    TIEMPO_FIN_PARTICIPACION_ACTIVIDAD       TIMESTAMP(6)     NOT NULL,
    TIEMPO_INICIO_PARTICIPACION_ACTIVIDAD    TIMESTAMP(6)     NOT NULL,
    INVITADO_ID                              VARCHAR2(40),
    CLAVE_CLIENTE_ID                         NUMBER(10, 0),
    CONSTRAINT ACTIVIDAD_PARTICIPACION_PK PRIMARY KEY (ACTIVIDAD_PARTICIPACION_ID)
)
;



-- 
-- INDEX: CLAVE_CLIENTE_PK 
--

CREATE INDEX CLAVE_CLIENTE_PK ON ACTIVIDAD_PARTICIPACION(CLAVE_CLIENTE_ID)
;
-- 
-- INDEX: CLAVE_INVITADO_ACTIVIDAD_FK 
--

CREATE INDEX CLAVE_INVITADO_ACTIVIDAD_FK ON ACTIVIDAD_PARTICIPACION(INVITADO_ID)
;
