-- 
-- TABLE: ACTIVIDAD_JUEGO 
--

CREATE TABLE ACTIVIDAD_JUEGO(
    ACTIVIDAD_ID         VARCHAR2(40)    NOT NULL,
    NOMBRE_JUEGO         VARCHAR2(40)    NOT NULL,
    DESCRIPCION_JUEGO    VARCHAR2(40)    NOT NULL,
    TIPO_JUEGO_ID        VARCHAR2(40)    NOT NULL,
    CONSTRAINT ACTIVIDAD_JUEGO_PK PRIMARY KEY (ACTIVIDAD_ID)
)
;



-- 
-- INDEX: "CLAVE_ACTIVIDAD_JUEGO_FK" 
--

CREATE INDEX "CLAVE_ACTIVIDAD_JUEGO_FK" ON ACTIVIDAD_JUEGO(ACTIVIDAD_ID)
;
-- 
-- INDEX: CLAVE_TIPO_JUEGO_ACT_JUEGO_FK 
--

CREATE INDEX CLAVE_TIPO_JUEGO_ACT_JUEGO_FK ON ACTIVIDAD_JUEGO(TIPO_JUEGO_ID)
;
