-- 
-- TABLE: ACTIVIDAD_DEPORTE 
--

CREATE TABLE ACTIVIDAD_DEPORTE(
    ACTIVIDAD_ID           VARCHAR2(40)    NOT NULL,
    NOMBRE_DEPORTE         VARCHAR2(40)    NOT NULL,
    DESCRIPCION_DEPORTE    VARCHAR2(40)    NOT NULL,
    TIPO_DEPORTE_ID        VARCHAR2(40)    NOT NULL,
    CONSTRAINT ACTIVIDAD_DEPORTE_PK PRIMARY KEY (ACTIVIDAD_ID)
)
;



-- 
-- INDEX: CLAVE_ACTIVIDAD_DEPORTE_FK 
--

CREATE INDEX CLAVE_ACTIVIDAD_DEPORTE_FK ON ACTIVIDAD_DEPORTE(ACTIVIDAD_ID)
;
-- 
-- INDEX: CLAVE_TIPO_DEPORTE_ACTIVIDAD_DEPORTE_FK 
--

CREATE INDEX CLAVE_TIPO_DEPORTE_ACTIVIDAD_DEPORTE_FK ON ACTIVIDAD_DEPORTE(TIPO_DEPORTE_ID)
;
