-- 
-- TABLE: ACTIVIDAD_CAMPAMENTO 
--

CREATE TABLE ACTIVIDAD_CAMPAMENTO(
    ACTIVIDAD_ID                     VARCHAR2(40)    NOT NULL,
    DURACION_CAMPAMENTO              VARCHAR2(40)    NOT NULL,
    UBICACION_LONGITUD_CAMPAMENTO    BINARY_FLOAT    NOT NULL,
    UBICACION_LATITUD_CAMPAMENTO     BINARY_FLOAT    NOT NULL,
    CALLE_CAMPAMENTO                 VARCHAR2(40)    NOT NULL,
    COLONIA_CAMPAMENTO               VARCHAR2(40)    NOT NULL,
    MUNICIPIO_CAMPAMENTO             VARCHAR2(40)    NOT NULL,
    CONSTRAINT ACTVIDAD_CAMPAMENTO_PK PRIMARY KEY (ACTIVIDAD_ID)
)
;



-- 
-- INDEX: Ref1319 
--

CREATE INDEX Ref1319 ON ACTIVIDAD_CAMPAMENTO(ACTIVIDAD_ID)
;
