-- 
-- TABLE: ACTIVIDAD 
--

CREATE TABLE ACTIVIDAD(
    ACTIVIDAD_ID             VARCHAR2(40)    NOT NULL,
    FECHA_FIN_TEMP           TIMESTAMP(6),
    FECHA_INICIO_TEMP        TIMESTAMP(6),
    COSTO_ACTIVIDAD          VARCHAR2(40)    NOT NULL,
    DESCRIPCION_ACTIVIDAD    VARCHAR2(40)    NOT NULL,
    CENTRO_ID                VARCHAR2(40)    NOT NULL,
    EMPLEADO_ID              VARCHAR2(40)    NOT NULL,
    CONSTRAINT ACTIVIDAD_PK PRIMARY KEY (ACTIVIDAD_ID)
)
;



-- 
-- INDEX: CLAVE_CENTRO_VAC_ACTIVIDAD_FK 
--

CREATE INDEX CLAVE_CENTRO_VAC_ACTIVIDAD_FK ON ACTIVIDAD(CENTRO_ID)
;
-- 
-- INDEX: CLAVE_LIDER_ACTIVIDAD_FK 
--

CREATE INDEX CLAVE_LIDER_ACTIVIDAD_FK ON ACTIVIDAD(EMPLEADO_ID)
;
