-- 
-- TABLE: ASOCIACION 
--

CREATE TABLE ASOCIACION(
    ASOCIACION_ID           VARCHAR2(40)    NOT NULL,
    NOMBRE_ASOCIACION       VARCHAR2(40)    NOT NULL,
    CALLE_ASOCIACION        VARCHAR2(40)    NOT NULL,
    MUNICIPIO_ASOCIACION    VARCHAR2(40)    NOT NULL,
    COLONIA_ASOCIACION      VARCHAR2(40)    NOT NULL,
    TELEFONO_ASOCIACION     VARCHAR2(40)    NOT NULL,
    CONSTRAINT ASOCIACION_PK PRIMARY KEY (ASOCIACION_ID)
)
;



