-- 
-- TABLE: AUTO_CLIENTE 
--

CREATE TABLE AUTO_CLIENTE(
    PLACA                  VARCHAR2(40)    NOT NULL,
    MODELO_AUTO_CLIENTE    VARCHAR2(40)    NOT NULL,
    MARCA_AUTO_CLIENTE     VARCHAR2(40)    NOT NULL,
    CONSTRAINT AUTO_CLIENTE_PK PRIMARY KEY (PLACA)
)
;



