-- 
-- TABLE: CENTRO_VACACIONAL 
--

CREATE TABLE CENTRO_VACACIONAL(
    CENTRO_ID                    VARCHAR2(40)    NOT NULL,
    UBICACION_LATITUD_CENTRO     BINARY_FLOAT    NOT NULL,
    UBICACION_LONGITUD_CENTRO    BINARY_FLOAT    NOT NULL,
    ASOCIACION_ID                VARCHAR2(40)    NOT NULL,
    CONSTRAINT CENTRO_VACACIONAL_PK PRIMARY KEY (CENTRO_ID)
)
;



-- 
-- INDEX: CLAVE_ASOCIACION_CENTRO_VAC_FK 
--

CREATE INDEX CLAVE_ASOCIACION_CENTRO_VAC_FK ON CENTRO_VACACIONAL(ASOCIACION_ID)
;
