-- 
-- TABLE: CENTRO_LIDER 
--

CREATE TABLE CENTRO_LIDER(
    CENTRO_ID      VARCHAR2(40)    NOT NULL,
    EMPLEADO_ID    VARCHAR2(40)    NOT NULL,
    CONSTRAINT CENTRO_LIDER_PK PRIMARY KEY (CENTRO_ID, EMPLEADO_ID)
)
;



-- 
-- INDEX: CLAVE_CENTRO_VAC_CENTRO_LID_FK 
--

CREATE INDEX CLAVE_CENTRO_VAC_CENTRO_LID_FK ON CENTRO_LIDER(CENTRO_ID)
;
-- 
-- INDEX: CLAVE_LIDER_CENTRO_LID_FK 
--

CREATE INDEX CLAVE_LIDER_CENTRO_LID_FK ON CENTRO_LIDER(EMPLEADO_ID)
;
