-- 
-- TABLE: CERTIFIACION_VERSION 
--

CREATE TABLE CERTIFIACION_VERSION(
    CERTIFICACION_VERSION_ID    NUMBER(10, 0)    NOT NULL,
    VERSION_NO_CERTIFICACION    NUMBER(38, 0)    NOT NULL,
    TEMARIO_PDF_VERSION         RAW(40)          NOT NULL,
    NIVEL_VERSION               VARCHAR2(40)     NOT NULL,
    OBJETIVO_VERSION            VARCHAR2(40)     NOT NULL,
    CERTIFICACION_ID            VARCHAR2(40),
    CONSTRAINT CERTIFICACION_VERSION_PK PRIMARY KEY (CERTIFICACION_VERSION_ID)
)
;



-- 
-- INDEX: CERTIFICACION_VERSION_UNIQUE 
--

CREATE UNIQUE INDEX CERTIFICACION_VERSION_UNIQUE ON CERTIFIACION_VERSION(VERSION_NO_CERTIFICACION)
;
-- 
-- INDEX: CLAVE_CERT_CERT_VERSION_FK 
--

CREATE INDEX CLAVE_CERT_CERT_VERSION_FK ON CERTIFIACION_VERSION(CERTIFICACION_ID)
;
