-- 
-- TABLE: CERTIFICACION 
--

CREATE TABLE CERTIFICACION(
    CERTIFICACION_ID        VARCHAR2(40)    NOT NULL,
    ASOCIACION_ID           VARCHAR2(40),
    NOMBRE_CERTIFICACION    VARCHAR2(40)    NOT NULL,
    CONSTRAINT CERTIFICACION_PK PRIMARY KEY (CERTIFICACION_ID)
)
;



-- 
-- INDEX: CLAVE_ASOC_CERT_FK 
--

CREATE INDEX CLAVE_ASOC_CERT_FK ON CERTIFICACION(ASOCIACION_ID)
;
