-- 
-- TABLE: CLIENTE_MEMBRESIA 
--

CREATE TABLE CLIENTE_MEMBRESIA(
    CLAVE_CLIENTE_ID                  NUMBER(10, 0)    NOT NULL,
    COSTO_MENSUAL                     BINARY_FLOAT     NOT NULL,
    NUM_MAX_INVITADOS                 NUMBER(40, 0)    NOT NULL,
    TIPO_TARJETA_CLIENTE_MEMBRESIA    VARCHAR2(40),
    CLIENTE_ASOCIADO_MEMBRESIA        VARCHAR2(40),
    FECHA_REGISTRO_MEMBRESIA          VARCHAR2(40),
    ESTADO_MEMBRESIA                  VARCHAR2(40)     NOT NULL,
    NO_TARJETA                        VARCHAR2(40),
    CONSTRAINT CLIENTE_MEMBRESIA_PK PRIMARY KEY (CLAVE_CLIENTE_ID)
)
;



-- 
-- INDEX: CLAVE_ESTADO_MEMBRESIA_FK 
--

CREATE INDEX CLAVE_ESTADO_MEMBRESIA_FK ON CLIENTE_MEMBRESIA(ESTADO_MEMBRESIA)
;
-- 
-- INDEX: CLAVE_TARJETA_MEMBRESIA_FK 
--

CREATE INDEX CLAVE_TARJETA_MEMBRESIA_FK ON CLIENTE_MEMBRESIA(NO_TARJETA)
;
-- 
-- INDEX: CLAVE_CLIENTE_MEM_CLIENTE_FK 
--

CREATE INDEX CLAVE_CLIENTE_MEM_CLIENTE_FK ON CLIENTE_MEMBRESIA(CLAVE_CLIENTE_ID)
;
