-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLAVE_CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    CURP_CLIENTE              VARCHAR2(40)     NOT NULL,
    NOMBRE_CLIENTE            VARCHAR2(40)     NOT NULL,
    ESTADO_CIVIL_CLIENTE      VARCHAR2(40)     NOT NULL,
    EDAD_CLIENTE              VARCHAR2(40)     NOT NULL,
    NIVEL_ESTUDIOS_CLIENTE    VARCHAR2(40)     NOT NULL,
    OCUPACION_CLIENTE         VARCHAR2(40)     NOT NULL,
    TELEFONO_CLIENTE          VARCHAR2(40)     NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLAVE_CLIENTE_ID)
)
;



