-- 
-- TABLE: EMPLEADO 
--

CREATE TABLE EMPLEADO(
    EMPLEADO_ID                  VARCHAR2(40)    NOT NULL,
    NOMBRE_EMPLEADO              VARCHAR2(40)    NOT NULL,
    APELLIDO_PATERNO_EMPLEADO    VARCHAR2(40)    NOT NULL,
    APELLIDO_MATERNO_EMPLEADO    VARCHAR2(40)    NOT NULL,
    TELEFONO_EMPLEADO            VARCHAR2(40)    NOT NULL,
    ASOCIACION_ID                VARCHAR2(40)    NOT NULL,
    EMPLEADO_RESPONSABLE_ID      VARCHAR2(40),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- INDEX: CLAVE_EMP_EMP_FK 
--

CREATE INDEX CLAVE_EMP_EMP_FK ON EMPLEADO(EMPLEADO_RESPONSABLE_ID)
;
-- 
-- INDEX: CLAVE_ASOC_EMPLEADO_FK 
--

CREATE INDEX CLAVE_ASOC_EMPLEADO_FK ON EMPLEADO(ASOCIACION_ID)
;
