-- 
-- TABLE: ESTADO_MEMBRESIA 
--

CREATE TABLE ESTADO_MEMBRESIA(
    ESTADO_MEMBRESIA           VARCHAR2(40)    NOT NULL,
    NOMBRE_ESTADO_MEMBRESIA    VARCHAR2(40)    NOT NULL
                               CONSTRAINT CK_NOMBRE_ESTADO_MEMBRESIA CHECK (UPPER(NOMBRE_ESTADO_MEMBRESIA) in ('VIGENTE','ADEUDO','SUSPENDIDA','CANCELADA')),
    DESCRIPCION_ESTADO         VARCHAR2(40)    NOT NULL,
    CONSTRAINT ESTADO_MEMBRESIA_PK PRIMARY KEY (ESTADO_MEMBRESIA)
)
;



