-- 
-- TABLE: HISTORIAL_MEMBRESIA 
--

CREATE TABLE HISTORIAL_MEMBRESIA(
    HISTORIAL_MEMBRESIA_ID    VARCHAR2(40)     NOT NULL,
    FECHA_CAMBIO_ESTADO       VARCHAR2(40)     NOT NULL,
    ESTADO_MEMBRESIA          VARCHAR2(40),
    CLAVE_CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORIAL_MEMBRESIA_PK PRIMARY KEY (HISTORIAL_MEMBRESIA_ID)
)
;



-- 
-- INDEX: CLAVE_HIST_CLIENTE_FK 
--

CREATE INDEX CLAVE_HIST_CLIENTE_FK ON HISTORIAL_MEMBRESIA(CLAVE_CLIENTE_ID)
;
-- 
-- INDEX: CLAVE_HIST_HESTADO_MEMBRESIA_FK 
--

CREATE INDEX CLAVE_HIST_HESTADO_MEMBRESIA_FK ON HISTORIAL_MEMBRESIA(ESTADO_MEMBRESIA)
;
