-- 
-- TABLE: IMAGEN_ACTIVIDAD 
--

CREATE TABLE IMAGEN_ACTIVIDAD(
    IMAGEN_ACTIVIDAD_ID    VARCHAR2(40)    NOT NULL,
    DATA_IMAGEN            BLOB            NOT NULL,
    ACTIVIDAD_ID           VARCHAR2(40)    NOT NULL,
    CONSTRAINT IMAGEN_ACTIVIDAD_PK PRIMARY KEY (IMAGEN_ACTIVIDAD_ID)
)
;



-- 
-- INDEX: CLAVE_ACTIVIDAD_IMAG_ACTIVIDAD_FK 
--

CREATE INDEX CLAVE_ACTIVIDAD_IMAG_ACTIVIDAD_FK ON IMAGEN_ACTIVIDAD(ACTIVIDAD_ID)
;
