-- 
-- TABLE: INVITADO 
--

CREATE TABLE INVITADO(
    INVITADO_ID            VARCHAR2(40)     NOT NULL,
    NOMBRE_COMPLETO        VARCHAR2(40)     NOT NULL,
    EDAD_INVITADO          VARCHAR2(40)     NOT NULL,
    PARENTESCO_INVITADO    VARCHAR2(40)     NOT NULL,
    OCUPACION_INVITADO     VARCHAR2(40)     NOT NULL,
    CLAVE_CLIENTE_ID       NUMBER(10, 0),
    CONSTRAINT INVITADO_PK PRIMARY KEY (INVITADO_ID)
)
;



-- 
-- INDEX: CLAVE_INVITADO_CLIENTE_FK 
--

CREATE INDEX CLAVE_INVITADO_CLIENTE_FK ON INVITADO(CLAVE_CLIENTE_ID)
;
