-- 
-- TABLE: LIDER_CERTIFICACION 
--

CREATE TABLE LIDER_CERTIFICACION(
    EMPLEADO_ID                 VARCHAR2(40)     NOT NULL,
    CERTIFICACION_VERSION_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_CERTIFIACION          TIMESTAMP(6)     NOT NULL,
    VERSION                     VARCHAR2(40)     NOT NULL,
    CONSTRAINT LIDER_CERTIFICACION_PK PRIMARY KEY (EMPLEADO_ID, CERTIFICACION_VERSION_ID)
)
;



-- 
-- INDEX: CLAVE_CERT_VER_LIDER_CERT_FK 
--

CREATE INDEX CLAVE_CERT_VER_LIDER_CERT_FK ON LIDER_CERTIFICACION(CERTIFICACION_VERSION_ID)
;
-- 
-- INDEX: CLAVE_LIDER_LIDER_CERT_FK 
--

CREATE INDEX CLAVE_LIDER_LIDER_CERT_FK ON LIDER_CERTIFICACION(EMPLEADO_ID)
;
