-- 
-- TABLE: LIDER 
--

CREATE TABLE LIDER(
    EMPLEADO_ID                VARCHAR2(40)     NOT NULL,
    ANIOS_EXPERIENCIA_LIDER    NUMBER(40, 0)    NOT NULL,
    ESPECIALIZACION_LIDER      VARCHAR2(40)     NOT NULL,
    CONSTRAINT LIDER_PK PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- INDEX: Ref614 
--

CREATE INDEX Ref614 ON LIDER(EMPLEADO_ID)
;
