-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    NO_TARJETA                VARCHAR2(40)    NOT NULL,
    ANIO_TARJETA              VARCHAR2(40),
    MES_EXPIRACION_TARJETA    VARCHAR2(40),
    TIPO_TARJETA              VARCHAR2(40),
    CONSTRAINT TARJETA_PK PRIMARY KEY (NO_TARJETA)
)
;



