-- 
-- TABLE: TIPO_DEPORTE 
--

CREATE TABLE TIPO_DEPORTE(
    TIPO_DEPORTE_ID                VARCHAR2(40)    NOT NULL,
    HORAS_ENTRENAMIENTO_DEPORTE    VARCHAR2(40)    NOT NULL,
    ACCESORIOS_DEPORTE             VARCHAR2(40)    NOT NULL,
    NOMBRE_DEPORTE                 VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (TIPO_DEPORTE_ID)
)
;



