-- 
-- TABLE: TIPO_JUEGO 
--

CREATE TABLE TIPO_JUEGO(
    TIPO_JUEGO_ID                   VARCHAR2(40)     NOT NULL,
    NOMBRE                          VARCHAR2(40)     NOT NULL,
    DESCRIPCION_JUEGO               VARCHAR2(40)     NOT NULL,
    CANTIDAD_PARTICIPANTES_JUEGO    NUMBER(38, 0)    NOT NULL
                                    CHECK (CANTIDAD_PARTICIPANTES_JUEGO > 1),
    CONSTRAINT PK17 PRIMARY KEY (TIPO_JUEGO_ID)
)
;



