-- 
-- TABLE: VISITA_INVITADO 
--

CREATE TABLE VISITA_INVITADO(
    INVITADO_ID          VARCHAR2(40)    NOT NULL,
    VISITA_CLIENTE_ID    VARCHAR2(40)    NOT NULL,
    CONSTRAINT VISITA_INVITADO_PK PRIMARY KEY (INVITADO_ID, VISITA_CLIENTE_ID)
)
;



-- 
-- INDEX: Ref3059 
--

CREATE INDEX Ref3059 ON VISITA_INVITADO(INVITADO_ID)
;
-- 
-- INDEX: CLAVE_VISITA_INVITADO_FK 
--

CREATE INDEX CLAVE_VISITA_INVITADO_FK ON VISITA_INVITADO(VISITA_CLIENTE_ID)
;
