-- 
-- TABLE: VISITA_CLIENTE 
--

CREATE TABLE VISITA_CLIENTE(
    VISITA_CLIENTE_ID             VARCHAR2(40)     NOT NULL,
    RCENTRO_ID                    VARCHAR2(40)     NOT NULL,
    FECHA_LLEGADA_REGISTRO        TIMESTAMP(6)     NOT NULL,
    FECHA_SLIDA_REGISTRO          TIMESTAMP(6)     NOT NULL,
    CANTIDAD_PERSONAS_REGISTRO    VARCHAR2(40)     NOT NULL,
    CLAVE_CLIENTE_ID              NUMBER(10, 0),
    PLACA                         VARCHAR2(40),
    CONSTRAINT VISITA_CLIENTE_PK PRIMARY KEY (VISITA_CLIENTE_ID)
)
;



-- 
-- INDEX: CLAVE_CLIENTE_FK 
--

CREATE INDEX CLAVE_CLIENTE_FK ON VISITA_CLIENTE(CLAVE_CLIENTE_ID)
;
-- 
-- INDEX: CLAVE_AUTO_CILENTE_FK 
--

CREATE INDEX CLAVE_AUTO_CILENTE_FK ON VISITA_CLIENTE(PLACA)
;
